---
AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS CloudFormation template for AWS Glue job
Resources:
  MyGlueSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for Glue Job.
      VpcId: !Ref VpcId

  GlueJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: !Ref GlueJobScriptLocation
        PythonVersion: '3'
      DefaultArguments:
        '--TempDir': !Ref TempDir
        '--enable-continuous-cloudwatch-log': 'true'
        '--enable-continuous-log-filter': 'true'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Name: !Ref GlueJobName
      Role: !Ref GlueExecutionRole
      SecurityConfiguration: !Ref GlueSecurityConfiguration
      WorkerType: Standard
      NumberOfWorkers: 10

  GlueSecurityConfiguration:
    Type: 'AWS::Glue::SecurityConfiguration'
    Properties:
      Name: !Ref GlueSecurityConfigurationName
      EncryptionConfiguration:
        S3Encryption:
          - S3EncryptionMode: SSEC
            KmsKeyArn: !Ref KMSKeyARN

Parameters:
  VpcId:
    Type: String
    Description: 'VPC ID'

  GlueJobScriptLocation:
    Type: String
    Description: 'The S3 location of the Glue Job script'
    
  TempDir:
    Type: String
    Description: 'The S3 location for the temp directory'
    
  GlueJobName:
    Type: String
    Description: 'The name of the Glue Job'

  GlueExecutionRole:
    Type: String
    Description: 'The role for the Glue Job to assume'

  GlueSecurityConfigurationName:
    Type: String
    Description: 'The name of the Glue security configuration'

  KMSKeyARN:
    Type: String
    Description: 'The ARN of the KMS key used for S3 server-side encryption'

Outputs:
  GlueJobName:
    Description: 'Name of the Glue job'
    Value: !Ref GlueJobName
